// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// srs_covar
List srs_covar(CharacterVector file, CharacterVector sample_names, double freq_thresh);
RcppExport SEXP _srsStuff_srs_covar(SEXP fileSEXP, SEXP sample_namesSEXP, SEXP freq_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sample_names(sample_namesSEXP);
    Rcpp::traits::input_parameter< double >::type freq_thresh(freq_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(srs_covar(file, sample_names, freq_thresh));
    return rcpp_result_gen;
END_RCPP
}
// srs_identity
List srs_identity(CharacterVector file, IntegerVector pops_of_indivs, int num_pops, int num_internal_nodes, List daughters, int BootReps);
RcppExport SEXP _srsStuff_srs_identity(SEXP fileSEXP, SEXP pops_of_indivsSEXP, SEXP num_popsSEXP, SEXP num_internal_nodesSEXP, SEXP daughtersSEXP, SEXP BootRepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pops_of_indivs(pops_of_indivsSEXP);
    Rcpp::traits::input_parameter< int >::type num_pops(num_popsSEXP);
    Rcpp::traits::input_parameter< int >::type num_internal_nodes(num_internal_nodesSEXP);
    Rcpp::traits::input_parameter< List >::type daughters(daughtersSEXP);
    Rcpp::traits::input_parameter< int >::type BootReps(BootRepsSEXP);
    rcpp_result_gen = Rcpp::wrap(srs_identity(file, pops_of_indivs, num_pops, num_internal_nodes, daughters, BootReps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_srsStuff_srs_covar", (DL_FUNC) &_srsStuff_srs_covar, 3},
    {"_srsStuff_srs_identity", (DL_FUNC) &_srsStuff_srs_identity, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_srsStuff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
