// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// srs_covar
List srs_covar(CharacterVector file, CharacterVector sample_names, double freq_thresh);
RcppExport SEXP _srsStuff_srs_covar(SEXP fileSEXP, SEXP sample_namesSEXP, SEXP freq_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sample_names(sample_namesSEXP);
    Rcpp::traits::input_parameter< double >::type freq_thresh(freq_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(srs_covar(file, sample_names, freq_thresh));
    return rcpp_result_gen;
END_RCPP
}
// srs_identity
List srs_identity(CharacterVector file, List groups, CharacterVector sample_names, int BootReps, double freq_thresh);
RcppExport SEXP _srsStuff_srs_identity(SEXP fileSEXP, SEXP groupsSEXP, SEXP sample_namesSEXP, SEXP BootRepsSEXP, SEXP freq_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type file(fileSEXP);
    Rcpp::traits::input_parameter< List >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sample_names(sample_namesSEXP);
    Rcpp::traits::input_parameter< int >::type BootReps(BootRepsSEXP);
    Rcpp::traits::input_parameter< double >::type freq_thresh(freq_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(srs_identity(file, groups, sample_names, BootReps, freq_thresh));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_srsStuff_srs_covar", (DL_FUNC) &_srsStuff_srs_covar, 3},
    {"_srsStuff_srs_identity", (DL_FUNC) &_srsStuff_srs_identity, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_srsStuff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
